name: EDOPro dependencies
on: push
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
    - name: Create release
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: false
        prerelease: false

  read-release:
    runs-on: ${{ matrix.os }}
    needs: create-release
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-18.04]
    steps:
    - name: Get upload endpoint
      id: get_endpoint
      shell: bash
      run: |
        curl -o latest.json https://api.github.com/repos/kevinlul/edopro-vcpkg-cache/releases/latest
        node --version
        node -e "console.log(JSON.parse(require('fs').readFileSync('./latest.json')))"
        node -e "console.log(JSON.parse(require('fs').readFileSync('./latest.json'))['upload_url'])"
        echo ::set-output name=upload_url::$(node -e "console.log(JSON.parse(require('fs').readFileSync('./latest.json'))['upload_url'])")
    - name: Echo Actions output
      shell: bash
      run: |
        echo ${{ steps.get_endpoint.outputs.upload_url }}
