name: vcpkg (x86-windows-static)
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install vcpkg
      shell: powershell
      run: |
        git clone --depth=1 https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        .\bootstrap-vcpkg.bat
    - name: Customize vcpkg
      shell: bash
      run: |
        echo -e "\nset(VCPKG_PLATFORM_TOOLSET v141)" >> vcpkg/triplets/community/x86-windows-static.cmake
    - name: Install dependencies
      shell: bash
      run: |
        cd vcpkg
        ./vcpkg install --triplet x86-windows-static --overlay-ports=../ports mpg123 || :
    - name: Upload mpg123
      uses: actions/upload-artifact@v1
      with:
        name: mpg123.zip
        path: vcpkg/buildtrees/mpg123
    - name: Upload tools
      uses: actions/upload-artifact@v1
      with:
        name: tools.zip
        path: vcpkg/downloads/tools
