name: vcpkg (x86-windows-static)
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install vcpkg
      shell: powershell
      run: |
        git clone --depth=1 https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        .\bootstrap-vcpkg.bat
    - name: Customize vcpkg
      shell: bash
      run: |
        echo -e "\nset(VCPKG_PLATFORM_TOOLSET v141)" >> vcpkg/triplets/community/x86-windows-static.cmake
    - name: Install dependencies
      shell: bash
      run: |
        cd vcpkg
        ./vcpkg install --triplet x86-windows-static \
          --overlay-ports=../ports \
          lua[cpp] \
          libevent sqlite3 \
          bzip2 libjpeg-turbo libpng zlib \
          curl openssl libgit2 fmt nlohmann-json \
          sdl2-mixer[libflac,mpg123,libvorbis] \
          discord-rpc-payload
    - name: Zip binaries
      shell: bash
      run: |
        cd vcpkg
        "$PROGRAMFILES/7-Zip/7z.exe" a -tzip installed_x86-windows-static.zip installed scripts .vcpkg-root vcpkg.exe
    - name: Upload binaries to GitHub
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: https://uploads.github.com/repos/kevinlul/edopro-vcpkg-cache/releases/22193553/assets{?name,label}
        asset_path: ./vcpkg/installed_x86-windows-static.zip
        asset_name: installed_x86-windows-static.zip
        asset_content_type: application/zip
